USE CLASSICMODELS;

DROP PROCEDURE IF EXISTS GET_ORDER_BY_CUST;

DELIMITER //

CREATE PROCEDURE GET_ORDER_BY_CUST(IN CUST_NO INT, OUT SHIPPED INT, OUT CANCELED INT)                  
  BEGIN
   -- SHIPPED
   SELECT COUNT(*) INTO SHIPPED FROM ORDERS
        WHERE  CUSTOMERNUMBER = CUST_NO
                  AND STATUS = 'SHIPPED';    
                  
   -- CANCELED
   SELECT COUNT(*) INTO CANCELED FROM ORDERS
        WHERE  CUSTOMERNUMBER = CUST_NO
                  AND STATUS = 'CANCELED';
  END//

DELIMITER ;

CALL GET_ORDER_BY_CUST(141,@SHIPPED,@CANCELED);
SELECT @SHIPPED,@CANCELED;