USE CLASSICMODELS;

DROP PROCEDURE IF EXISTS GETCUSTOMERLEVEL;

DELIMITER //

CREATE PROCEDURE GETCUSTOMERLEVEL(IN  P_CUSTOMERNUMBER INT(11), OUT P_CUSTOMERLEVEL  VARCHAR(10))   
  BEGIN
      DECLARE CREDITLIM DOUBLE;
   
      SELECT CREDITLIMIT INTO CREDITLIM FROM CUSTOMERS
      WHERE CUSTOMERNUMBER = P_CUSTOMERNUMBER;
   
      IF CREDITLIM > 50000 THEN
      
        SET P_CUSTOMERLEVEL = 'PLATINUM';
        
      ELSEIF (CREDITLIM <= 50000 AND CREDITLIM >= 10000) THEN
      
        SET P_CUSTOMERLEVEL = 'GOLD';
        
      ELSEIF CREDITLIM < 10000 THEN
      
        SET P_CUSTOMERLEVEL = 'SILVER';
        
      END IF;
   
  END//

DELIMITER ;

CALL GETCUSTOMERLEVEL(307, @CUSTOMERLEVEL);
SELECT @CUSTOMERLEVEL;